DROP TABLE IF EXISTS TRANSFERENCIAS;
DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE usuarios (
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	balance FLOAT CHECK (balance >= 0) NOT NULL
);

CREATE TABLE transferencias (
	id SERIAL PRIMARY KEY,
	emisor INT,
	receptor INT,
	monto FLOAT,
	fecha TIMESTAMP,
	FOREIGN KEY (emisor) REFERENCES usuarios(id) ON DELETE CASCADE,
	FOREIGN KEY (receptor) REFERENCES usuarios(id) ON DELETE CASCADE
);

INSERT INTO USUARIOS (NOMBRE,BALANCE) VALUES 
('ALEXIS QUINTANILLA',50000),
('BALTASAR QUINTANILLA',100000),
('ELIANA VALDERRAMA', 70000);

